### ISSUE TITLE
Factor.io website cannot be reached via www.factor.io address

### ISSUE THREAD

**Issue by ArgonCode** [factor-io/factor#42]
The website cannot be reached if `www` is included in the address. The following error message is displayed:

ERROR
The request could not be satisfied.
Bad request. 
Generated by cloudfront (CloudFront)
Request ID: (...)

**Comment by skierkowski** [comment]
Fixed.

To fix the issue I created a new S3 bucket for www.factor.io and setup an A record DNS route with aliasing to that S3 bucket. The S3 bucket is configured to route www.factor.io to factor.io.
